apiVersion: v1
kind: Service
metadata:
  name: orderservice-postgres-headless
spec:
  clusterIP: None
  selector:
    app: orderservice-postgres
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: orderservice-postgres
spec:
  selector:
    app: orderservice-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
