apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderservice-postgres
spec:
  serviceName: orderservice-postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: orderservice-postgres
  template:
    metadata:
      labels:
        app: orderservice-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orderservicedb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: orderservice-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: orderservice-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
