apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-app-configmap
data:
  USER_SERVICE_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://userservice-postgres:5432/userservicedb"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_REDIS_HOST: "userservice-redis"
  SPRING_REDIS_PORT: "6379"


  SPRING_DATASOURCE_PASSWORD: password
  SERVICE_SECRET: "12345"
  INTERNAL_SECRET: "12345"
