apiVersion: v1
kind: Secret
metadata:
  name: authservice-app-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "example"
  SERVICE_SECRET: "example"
  INTERNAL_SECRET: "example"
  JWT_SECRET: "example"
  JWT_ACCESS_EXPIRATION: "example"
  JWT_REFRESH_EXPIRATION: "example"
