apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: userservice-postgres
spec:
  serviceName: userservice-postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: userservice-postgres
  template:
    metadata:
      labels:
        app: userservice-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          env:
            - name: POSTGRES_DB
              value: userservicedb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: userservice-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: userservice-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
