apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice-app
  template:
    metadata:
      labels:
        app: authservice-app
    spec:
      containers:
        - name: authservice-app
          image: authservice-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: authservice-app-configmap
            - secretRef:
                name: authservice-app-secret
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 3
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 768Mi
              cpu: 500m